[package]
name        = "hammer"
version     = "0.0.1"
edition     = "2021"
authors     = ["HackerOS Team <hackeros068@gmail.com>"]
description = "Atomic Debian package manager — rpm-ostree model, changes after reboot"
license     = "Apache-2.0"
repository  = "https://github.com/HackerOS-Linux-System/hammer/"

[[bin]]
name = "hammer"
path = "source-code/main.rs"

[dependencies]
anyhow          = "1"
tokio           = { version = "1", features = ["full"] }
reqwest         = { version = "0.11", default-features = false, features = ["json", "gzip", "deflate", "stream", "rustls-tls"] }
serde           = { version = "1", features = ["derive"] }
serde_json      = "1"
toml            = "0.5"
rusqlite        = { version = "0.31", features = ["bundled"] }
chrono          = { version = "0.4", features = ["serde"] }
indicatif       = "0.17"
owo-colors      = "3"
lexopt          = "0.3"
tar             = "0.4"
flate2          = "1"
xz2             = "0.1"
bzip2           = "0.4"
zstd            = "0.13"
futures-util    = "0.3"
terminal_size   = "0.3"
libc            = "0.2"
sha2            = "0.10"
sha1            = "0.10"
hex             = "0.4"
walkdir         = "2"
nix             = { version = "0.27", features = ["user"] }
axum            = "0.7"
tower           = "0.4"
tower-http      = { version = "0.5", features = ["cors"] }
hk-parser       = "0.3.0"
