use anyhow::{Context, Result};
use std::path::Path;

use crate::profile::{Generation, GenerationsDb};
use crate::log;

pub const GRUB_GENERATOR:   &str = "/etc/grub.d/09_hammer";
pub const GRUB_DEFAULTS:    &str = "/etc/default/grub.d/hammer.cfg";
pub const GRUB_GENS_FILE:   &str = "/boot/grub/hammer-generations";
pub const GRUB_CFG:         &str = "/boot/grub/grub.cfg";
pub const GRUB_TIMEOUT_ADD: u32  = 0;   // extra seconds added to GRUB timeout

// ─────────────────────────────────────────────────────────────
//  Entry point — called after every transaction
// ─────────────────────────────────────────────────────────────

/// Update GRUB after a transaction. Regenerates grub.cfg if grub-mkconfig is available.
pub fn update_grub(gens_db: &GenerationsDb) -> Result<()> {
    // Always write the machine-readable generations file (used by initramfs)
    write_generations_file(gens_db)
    .context("Writing hammer-generations file")?;

    // Install generator script
    install_generator()
    .context("Installing /etc/grub.d/09_hammer")?;

    // Install GRUB defaults
    install_defaults()
    .context("Installing GRUB defaults")?;

    // Regenerate grub.cfg if grub-mkconfig is present
    if Path::new("/usr/sbin/grub-mkconfig").exists()
        || Path::new("/usr/bin/grub-mkconfig").exists()
        || Path::new("/sbin/grub-mkconfig").exists()
        {
            regenerate_grub_cfg()?;
        } else {
            log::info("grub: grub-mkconfig not found, skipping grub.cfg regeneration");
        }

        Ok(())
}

// ─────────────────────────────────────────────────────────────
//  Machine-readable generations list
// ─────────────────────────────────────────────────────────────

fn write_generations_file(gens_db: &GenerationsDb) -> Result<()> {
    std::fs::create_dir_all("/boot/grub")?;

    let mut lines = Vec::new();
    lines.push(format!("# hammer generations — auto-generated, do not edit"));
    lines.push(format!("current={}", gens_db.current));
    if let Some(p) = gens_db.pending {
        lines.push(format!("pending={}", p));
    }

    let mut gens: Vec<_> = gens_db.generations.iter().collect();
    gens.sort_by(|a, b| b.number.cmp(&a.number));

    for gen in gens {
        let note = gen.note.as_deref().unwrap_or("").replace('\n', " ");
        let ts   = gen.timestamp.format("%Y-%m-%d %H:%M").to_string();
        lines.push(format!(
            "gen {} {} {} pkgs \"{}\"",
            gen.number,
            gen.profile_path().display(),
                           gen.package_count(),
                           format!("{} — {}", ts, note)
        ));
    }

    let content = lines.join("\n") + "\n";
    let tmp = format!("{}.tmp", GRUB_GENS_FILE);
    std::fs::write(&tmp, &content)?;
    std::fs::rename(&tmp, GRUB_GENS_FILE)?;
    log::info("grub: wrote hammer-generations");
    Ok(())
}

// ─────────────────────────────────────────────────────────────
//  GRUB generator script (/etc/grub.d/09_hammer)
// ─────────────────────────────────────────────────────────────

fn install_generator() -> Result<()> {
    std::fs::create_dir_all("/etc/grub.d")?;

    // Read kernel and initrd from current boot
    // We use the same kernel as current boot - hammer only manages userspace
    let script = r###"#!/bin/sh
    # /etc/grub.d/09_hammer - hammer generation menu entries
    # Auto-generated by hammer. Do not edit.
    set -e

    GENS_FILE="/boot/grub/hammer-generations"

    [ -f "$GENS_FILE" ] || exit 0

    . /usr/share/grub/grub-mkconfig_lib 2>/dev/null || true

    # Read current kernel info from /boot
    KERNEL=""
    INITRD=""
    ROOT_UUID=$(findmnt -n -o UUID /)

    for vmlinuz in /boot/vmlinuz-* /vmlinuz; do
        [ -f "$vmlinuz" ] && KERNEL="$vmlinuz" && break
        done
        for initrd_f in /boot/initrd.img-* /boot/initramfs-* /initrd.img; do
            [ -f "$initrd_f" ] && INITRD="$initrd_f" && break
            done

            [ -z "$KERNEL" ] && exit 0

            CURRENT=$(grep '^current=' "$GENS_FILE" | cut -d= -f2)
            PENDING=$(grep '^pending=' "$GENS_FILE" | cut -d= -f2)

            echo "# BEGIN hammer generations"

            # Parse gen entries: gen N /path N_pkgs "description"
            grep '^gen ' "$GENS_FILE" | while read _ GEN_N GEN_PATH GEN_PKGS GEN_DESC; do
            if [ "$GEN_N" = "$CURRENT" ]; then
                LABEL="Debian GNU/Linux (hammer gen-$GEN_N - current)"
                elif [ "$GEN_N" = "$PENDING" ]; then
                LABEL="Debian GNU/Linux (hammer gen-$GEN_N - pending)"
                else
                    LABEL="Debian GNU/Linux (hammer gen-$GEN_N - rollback)"
                    fi

                    echo "menuentry $LABEL --class debian --class gnu-linux --class gnu --class os {"
                    echo "    load_video"
                    echo "    insmod gzio"
                    echo "    insmod part_gpt"
                    echo "    insmod ext2"
                    if [ -n "$ROOT_UUID" ]; then
                        echo "    search --no-floppy --fs-uuid --set=root $ROOT_UUID"
                        LINUX_ROOT="root=UUID=$ROOT_UUID"
                        else
                            LINUX_ROOT="root=/dev/sda1"
                            fi
                            echo "    echo Loading hammer gen-$GEN_N kernel..."
                            echo "    linux   $KERNEL $LINUX_ROOT ro quiet splash hammer_gen=$GEN_N"
                            if [ -n "$INITRD" ]; then
                                echo "    echo Loading initial ramdisk..."
                                echo "    initrd  $INITRD"
                                fi
                                echo "}"
                                echo ""
                                done

                                echo "# END hammer generations"
                                "###;

                            let existing = std::fs::read_to_string(GRUB_GENERATOR).unwrap_or_default();
                            if existing != script {
                                std::fs::write(GRUB_GENERATOR, script)?;
                                // Make executable
                                let mut perms = std::fs::metadata(GRUB_GENERATOR)?.permissions();
                                std::os::unix::fs::PermissionsExt::set_mode(&mut perms, 0o755);
                                std::fs::set_permissions(GRUB_GENERATOR, perms)?;
                                log::info("grub: installed /etc/grub.d/09_hammer");
                            }
                            Ok(())
}

// ─────────────────────────────────────────────────────────────
//  GRUB defaults
// ─────────────────────────────────────────────────────────────

fn install_defaults() -> Result<()> {
    std::fs::create_dir_all("/etc/default/grub.d")?;

    let defaults = r#"# hammer GRUB configuration
    # Auto-generated. Edit with care.

    # Show the GRUB menu for at least this many seconds when generations are pending
    GRUB_TIMEOUT_STYLE="menu"
    GRUB_TIMEOUT=5

    # hammer generation is passed via kernel cmdline: hammer_gen=N
    "#;

    let path     = Path::new(GRUB_DEFAULTS);
    let existing = std::fs::read_to_string(path).unwrap_or_default();
    if existing != defaults {
        std::fs::write(path, defaults)?;
        log::info("grub: wrote GRUB defaults");
    }
    Ok(())
}

// ─────────────────────────────────────────────────────────────
//  grub-mkconfig
// ─────────────────────────────────────────────────────────────

fn regenerate_grub_cfg() -> Result<()> {
    log::info("grub: running grub-mkconfig...");

    let out = std::process::Command::new("grub-mkconfig")
    .arg("-o").arg(GRUB_CFG)
    .output()
    .context("Failed to run grub-mkconfig")?;

    if out.status.success() {
        log::info("grub: grub.cfg regenerated");
    } else {
        let err = String::from_utf8_lossy(&out.stderr);
        log::warn(&format!("grub: grub-mkconfig warnings: {}", err.lines().next().unwrap_or("")));
    }
    Ok(())
}

// ─────────────────────────────────────────────────────────────
//  Boot-time: read hammer_gen from cmdline
// ─────────────────────────────────────────────────────────────

/// Read which generation was selected at boot from kernel cmdline.
/// Returns None if no hammer_gen= was passed (use default/pending).
pub fn read_boot_gen() -> Option<u32> {
    let cmdline = std::fs::read_to_string("/proc/cmdline").ok()?;
    for token in cmdline.split_whitespace() {
        if let Some(val) = token.strip_prefix("hammer_gen=") {
            return val.parse().ok();
        }
    }
    None
}

/// Format a human-readable GRUB status string for `hammer status`
pub fn grub_status() -> String {
    let grub_cfg_ok = Path::new(GRUB_CFG).exists();
    let gens_file_ok = Path::new(GRUB_GENS_FILE).exists();
    let generator_ok = Path::new(GRUB_GENERATOR).exists();

    if grub_cfg_ok && gens_file_ok && generator_ok {
        "installed (grub.cfg, generator, generations file)".to_string()
    } else if generator_ok {
        "generator installed, grub.cfg not yet regenerated".to_string()
    } else {
        "not installed — run `hammer init`".to_string()
    }
}
