use anyhow::{Context, Result};
use std::path::Path;

use crate::profile::GenerationsDb;
use crate::log;

pub const GRUB_GENERATOR:  &str = "/etc/grub.d/09_hammer";
pub const GRUB_DEFAULTS:   &str = "/etc/default/grub.d/hammer.cfg";
pub const GRUB_GENS_FILE:  &str = "/boot/grub/hammer-generations";
pub const GRUB_CFG:        &str = "/boot/grub/grub.cfg";

const OS_NAME: &str = "HackerOS GNU/Linux";

// ─────────────────────────────────────────────────────────────
//  Entry point
// ─────────────────────────────────────────────────────────────

pub fn update_grub(gens_db: &GenerationsDb) -> Result<()> {
    write_generations_file(gens_db).context("Writing hammer-generations file")?;
    install_generator(gens_db).context("Installing /etc/grub.d/09_hammer")?;
    install_defaults().context("Installing GRUB defaults")?;

    if Path::new("/usr/sbin/grub-mkconfig").exists()
        || Path::new("/usr/bin/grub-mkconfig").exists()
        || Path::new("/sbin/grub-mkconfig").exists()
        {
            regenerate_grub_cfg()?;
        } else {
            log::info("grub: grub-mkconfig not found, skipping grub.cfg regeneration");
        }
        Ok(())
}

// ─────────────────────────────────────────────────────────────
//  Machine-readable generations file
// ─────────────────────────────────────────────────────────────

fn write_generations_file(gens_db: &GenerationsDb) -> Result<()> {
    std::fs::create_dir_all("/boot/grub")?;
    let mut lines = Vec::new();
    lines.push("# hammer generations — auto-generated, do not edit".to_string());
    lines.push(format!("current={}", gens_db.current));
    if let Some(p) = gens_db.pending { lines.push(format!("pending={}", p)); }

    let mut gens: Vec<_> = gens_db.generations.iter().collect();
    gens.sort_by(|a, b| b.number.cmp(&a.number));
    for gen in gens {
        let note = gen.note.as_deref().unwrap_or("").replace('\n', " ");
        let ts   = gen.timestamp.format("%Y-%m-%d %H:%M").to_string();
        // Date string for old(YYYY.MM.DD) label
        let date_label = gen.timestamp.format("%Y.%m.%d").to_string();
        lines.push(format!(
            "gen {} {} {} pkgs \"{}\" date={}",
            gen.number,
            gen.profile_path().display(),
                           gen.package_count(),
                           format!("{} — {}", ts, note),
                               date_label,
        ));
    }
    let content = lines.join("\n") + "\n";
    let tmp = format!("{}.tmp", GRUB_GENS_FILE);
    std::fs::write(&tmp, &content)?;
    std::fs::rename(&tmp, GRUB_GENS_FILE)?;
    log::info("grub: wrote hammer-generations");
    Ok(())
}

// ─────────────────────────────────────────────────────────────
//  GRUB generator script
//
//  Naming convention:
//    Current generation  → "HackerOS GNU/Linux"            (default, no suffix)
//    Pending generation  → "HackerOS GNU/Linux (pending)"
//    Older generations   → "HackerOS GNU/Linux old(YYYY.MM.DD)"
//
//  Menu structure:
//    HackerOS GNU/Linux                           ← default (current)
//    HackerOS GNU/Linux (pending)                 ← if staged
//    HackerOS GNU/Linux old(YYYY.MM.DD)           ← most recent rollback
//    Advanced HackerOS options >
//      HackerOS GNU/Linux                         ← current
//      HackerOS GNU/Linux old(YYYY.MM.DD)         ← each older gen
//      HackerOS GNU/Linux old(YYYY.MM.DD) recovery
//      …
// ─────────────────────────────────────────────────────────────

fn install_generator(_gens_db: &GenerationsDb) -> Result<()> {
    std::fs::create_dir_all("/etc/grub.d")?;

    // Build Rust-side label map so we can embed labels directly
    // instead of doing complex awk in the shell script.
    // The shell script reads hammer-generations and we embed
    // the label logic inline via awk pattern matching.

    let script = format!(r###"#!/bin/sh
    # /etc/grub.d/09_hammer  —  HackerOS generation menu entries
    # Auto-generated by hammer. Do not edit.
    #
    # Label convention:
    #   current generation → "{os_name}"
    #   pending generation → "{os_name} (pending)"
    #   older generations  → "{os_name} old(YYYY.MM.DD)"
    set -e

    OS_NAME="{os_name}"
    GENS_FILE="/boot/grub/hammer-generations"

    [ -f "$GENS_FILE" ] || exit 0

    . /usr/share/grub/grub-mkconfig_lib 2>/dev/null || true

    # ── Detect kernel / initrd ────────────────────────────────────
    KERNEL=""
    INITRD=""
    ROOT_UUID=$(findmnt -n -o UUID / 2>/dev/null || true)

    for vmlinuz in /boot/vmlinuz-* /vmlinuz; do
        [ -f "$vmlinuz" ] && KERNEL="$vmlinuz" && break
        done
        for initrd_f in /boot/initrd.img-* /boot/initramfs-* /initrd.img; do
            [ -f "$initrd_f" ] && INITRD="$initrd_f" && break
            done

            [ -z "$KERNEL" ] && exit 0

            # ── Read state ────────────────────────────────────────────────
            CURRENT=$(grep '^current=' "$GENS_FILE" | cut -d= -f2)
    PENDING=$(grep '^pending=' "$GENS_FILE" | cut -d= -f2)

    # ── Linux args ────────────────────────────────────────────────
    if [ -n "$ROOT_UUID" ]; then
        LINUX_ROOT="root=UUID=$ROOT_UUID"
        else
            LINUX_ROOT="root=/dev/sda1"
            fi

            # ── Helper: emit one menuentry ────────────────────────────────
            emit_entry() {{
            GEN_N="$1"
            LABEL="$2"
            EXTRA_ARGS="$3"
            echo "menuentry \"$LABEL\" --class hackeros --class gnu-linux --class gnu --class os {{"
            echo "    load_video"
            echo "    insmod gzio"
            echo "    insmod part_gpt"
            echo "    insmod ext2"
            if [ -n "$ROOT_UUID" ]; then
                echo "    search --no-floppy --fs-uuid --set=root $ROOT_UUID"
                fi
                echo "    echo 'Loading $LABEL…'"
                echo "    linux   $KERNEL $LINUX_ROOT ro quiet splash hammer_gen=$GEN_N $EXTRA_ARGS"
                [ -n "$INITRD" ] && echo "    initrd  $INITRD"
                echo "}}"
                echo ""
}}

# Get date label for a generation number from the gens file
get_date() {{
local gen_n="$1"
grep "^gen $gen_n " "$GENS_FILE" | sed 's/.*date=\([^ ]*\).*/\1/' | head -1
}}

echo "# BEGIN HackerOS hammer generations"

# ── Current generation — label is just the OS name (default) ──
emit_entry "$CURRENT" "$OS_NAME" ""

# ── Pending generation (if any) ───────────────────────────────
if [ -n "$PENDING" ] && [ "$PENDING" != "$CURRENT" ]; then
    emit_entry "$PENDING" "$OS_NAME (pending)" ""
    fi

    # ── Previous generation — old(YYYY.MM.DD) ─────────────────────
    PREV=$(grep '^gen ' "$GENS_FILE" | awk -v cur="$CURRENT" '{{
    split($0, a, " ")
    n = a[2]
    if (n < cur) {{ if (prev == "" || n > prev) prev = n }}
}} END {{ print prev }}')

    if [ -n "$PREV" ] && [ "$PREV" != "$CURRENT" ] && [ "$PREV" != "$PENDING" ]; then
        PREV_DATE=$(get_date "$PREV")
    emit_entry "$PREV" "$OS_NAME old($PREV_DATE)" ""
    fi

    # ── Advanced submenu with ALL generations ─────────────────────
    echo "submenu 'Advanced HackerOS options >' {{"

    # Current first in submenu (no date suffix = current)
    emit_entry "$CURRENT" "$OS_NAME" ""

    # All older generations, newest first
    grep '^gen ' "$GENS_FILE" | sort -rn -k2 | while read _ GEN_N GEN_PATH GEN_PKGS rest; do
    if [ "$GEN_N" = "$CURRENT" ]; then
        continue  # already emitted above
        fi

        GEN_DATE=$(get_date "$GEN_N")

    if [ "$GEN_N" = "$PENDING" ]; then
        GLABEL="$OS_NAME (pending)"
        else
            GLABEL="$OS_NAME old($GEN_DATE)"
            fi

            emit_entry "$GEN_N" "$GLABEL" ""
            # Recovery entry
            emit_entry "$GEN_N" "$GLABEL (recovery)" "single"
            done

            echo "}}"

            echo "# END HackerOS hammer generations"
            "###,
            os_name = OS_NAME,
    );

    let existing = std::fs::read_to_string(GRUB_GENERATOR).unwrap_or_default();
    if existing != script {
        std::fs::write(GRUB_GENERATOR, &script)?;
        let mut perms = std::fs::metadata(GRUB_GENERATOR)?.permissions();
        std::os::unix::fs::PermissionsExt::set_mode(&mut perms, 0o755);
        std::fs::set_permissions(GRUB_GENERATOR, perms)?;
        log::info("grub: installed /etc/grub.d/09_hammer");
    }
    Ok(())
}

// ─────────────────────────────────────────────────────────────
//  GRUB defaults
// ─────────────────────────────────────────────────────────────

fn install_defaults() -> Result<()> {
    std::fs::create_dir_all("/etc/default/grub.d")?;
    let defaults = format!(
        "# HackerOS hammer GRUB configuration — auto-generated\n\
GRUB_DISTRIBUTOR=\"{}\"\n\
GRUB_TIMEOUT_STYLE=\"menu\"\n\
GRUB_TIMEOUT=5\n\
# hammer generation is passed via kernel cmdline: hammer_gen=N\n",
OS_NAME
    );

    let path     = Path::new(GRUB_DEFAULTS);
    let existing = std::fs::read_to_string(path).unwrap_or_default();
    if existing != defaults {
        std::fs::write(path, &defaults)?;
        log::info("grub: wrote HackerOS GRUB defaults");
    }
    Ok(())
}

// ─────────────────────────────────────────────────────────────
//  grub-mkconfig
// ─────────────────────────────────────────────────────────────

fn regenerate_grub_cfg() -> Result<()> {
    log::info("grub: running grub-mkconfig...");
    let out = std::process::Command::new("grub-mkconfig")
    .arg("-o").arg(GRUB_CFG)
    .output().context("Failed to run grub-mkconfig")?;
    if out.status.success() {
        log::info("grub: grub.cfg regenerated");
    } else {
        let err = String::from_utf8_lossy(&out.stderr);
        log::warn(&format!("grub: grub-mkconfig warnings: {}",
                           err.lines().next().unwrap_or("")));
    }
    Ok(())
}

// ─────────────────────────────────────────────────────────────
//  Boot-time: read hammer_gen from cmdline
// ─────────────────────────────────────────────────────────────

pub fn read_boot_gen() -> Option<u32> {
    let cmdline = std::fs::read_to_string("/proc/cmdline").ok()?;
    for token in cmdline.split_whitespace() {
        if let Some(val) = token.strip_prefix("hammer_gen=") {
            return val.parse().ok();
        }
    }
    None
}

pub fn grub_status() -> String {
    let grub_cfg_ok  = Path::new(GRUB_CFG).exists();
    let gens_file_ok = Path::new(GRUB_GENS_FILE).exists();
    let generator_ok = Path::new(GRUB_GENERATOR).exists();
    if grub_cfg_ok && gens_file_ok && generator_ok {
        "installed (grub.cfg, generator, generations file)".to_string()
    } else if generator_ok {
        "generator installed, grub.cfg not yet regenerated".to_string()
    } else {
        "not installed — run `hammer init`".to_string()
    }
}

// ─────────────────────────────────────────────────────────────
//  Bootloader detection and multi-backend support
// ─────────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
pub enum BootloaderKind {
    GrubBios,
    GrubEfi,
    SystemdBoot,
    Unknown,
}

impl std::fmt::Display for BootloaderKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BootloaderKind::GrubBios    => write!(f, "GRUB (BIOS)"),
            BootloaderKind::GrubEfi     => write!(f, "GRUB (EFI)"),
            BootloaderKind::SystemdBoot => write!(f, "systemd-boot"),
            BootloaderKind::Unknown     => write!(f, "unknown"),
        }
    }
}

/// Detect which bootloader is managing this system.
pub fn detect_bootloader() -> BootloaderKind {
    // systemd-boot: /boot/efi/EFI/systemd or /efi/EFI/systemd
    let sdb_paths = [
        "/boot/efi/EFI/systemd/systemd-bootx64.efi",
        "/efi/EFI/systemd/systemd-bootx64.efi",
        "/boot/EFI/systemd/systemd-bootx64.efi",
    ];
    if sdb_paths.iter().any(|p| std::path::Path::new(p).exists()) {
        return BootloaderKind::SystemdBoot;
    }

    // Check bootctl --print-esp
    if let Ok(out) = std::process::Command::new("bootctl")
        .arg("is-installed")
        .output()
    {
        if out.status.success() {
            return BootloaderKind::SystemdBoot;
        }
    }

    // GRUB EFI: grubx64.efi in EFI partition
    let grub_efi_paths = [
        "/boot/efi/EFI/grub/grubx64.efi",
        "/boot/efi/EFI/ubuntu/grubx64.efi",
        "/boot/efi/EFI/debian/grubx64.efi",
        "/boot/efi/EFI/HackerOS/grubx64.efi",
    ];
    if grub_efi_paths.iter().any(|p| std::path::Path::new(p).exists()) {
        return BootloaderKind::GrubEfi;
    }

    // GRUB BIOS: /boot/grub/grub.cfg
    if std::path::Path::new("/boot/grub/grub.cfg").exists() {
        return BootloaderKind::GrubBios;
    }

    BootloaderKind::Unknown
}

// ─────────────────────────────────────────────────────────────
//  systemd-boot entries management
// ─────────────────────────────────────────────────────────────

/// Write a systemd-boot entry for a hammer generation.
pub fn write_systemd_boot_entry(gen_num: u32, _gen: &crate::profile::Generation) -> Result<()> {
    // Find the ESP
    let esp = find_esp()?;
    let entries_dir = esp.join("loader/entries");
    std::fs::create_dir_all(&entries_dir)?;

    let entry_path = entries_dir.join(format!("hammer-gen-{}.conf", gen_num));

    // Detect kernel and initrd
    let (kernel, initrd) = find_kernel_initrd()?;
    let cmdline = read_current_cmdline()?;

    let content = format!(
        "# hammer gen-{} — written by hammer v{}\n\
         title   HackerOS (gen-{})\n\
         linux   {}\n\
         initrd  {}\n\
         options {} hammer.gen={}\n",
        gen_num,
        env!("CARGO_PKG_VERSION"),
        gen_num,
        kernel,
        initrd,
        cmdline,
        gen_num,
    );

    std::fs::write(&entry_path, content)
        .with_context(|| format!("Writing systemd-boot entry {}", entry_path.display()))?;

    log::info(&format!("grub: wrote systemd-boot entry for gen-{}", gen_num));
    Ok(())
}

/// Write a systemd-boot loader.conf pointing to the active generation.
pub fn set_systemd_boot_default(gen_num: u32) -> Result<()> {
    let esp     = find_esp()?;
    let loader  = esp.join("loader/loader.conf");
    let content = format!(
        "# Written by hammer v{}\n\
         default hammer-gen-{}.conf\n\
         timeout 5\n\
         editor  no\n",
        env!("CARGO_PKG_VERSION"), gen_num
    );
    std::fs::write(&loader, content)?;
    log::info(&format!("grub: set systemd-boot default to gen-{}", gen_num));
    Ok(())
}

/// Remove the systemd-boot entry for a generation.
pub fn remove_systemd_boot_entry(gen_num: u32) -> Result<()> {
    let esp   = find_esp()?;
    let entry = esp.join("loader/entries").join(format!("hammer-gen-{}.conf", gen_num));
    if entry.exists() { std::fs::remove_file(&entry)?; }
    Ok(())
}

/// Update bootloader (GRUB or systemd-boot) for all generations.
pub fn update_all_bootloader_entries(gens_db: &crate::profile::GenerationsDb) -> Result<()> {
    let kind = detect_bootloader();
    match kind {
        BootloaderKind::GrubBios | BootloaderKind::GrubEfi => {
            update_grub(gens_db)?;
        }
        BootloaderKind::SystemdBoot => {
            for gen in gens_db.all() {
                write_systemd_boot_entry(gen.number, gen)?;
            }
            if let Some(active) = gens_db.active_num() {
                set_systemd_boot_default(active)?;
            }
        }
        BootloaderKind::Unknown => {
            log::warn("grub: unknown bootloader — cannot write boot entries");
        }
    }
    Ok(())
}

// ─────────────────────────────────────────────────────────────
//  Helpers
// ─────────────────────────────────────────────────────────────

fn find_esp() -> Result<std::path::PathBuf> {
    // Check common ESP mount points
    for path in &["/boot/efi", "/efi", "/boot"] {
        let p = std::path::Path::new(path);
        if p.join("EFI").exists() || p.join("loader").exists() {
            return Ok(p.to_path_buf());
        }
    }
    // Try findmnt
    if let Ok(out) = std::process::Command::new("findmnt")
        .args(["-n", "-o", "TARGET", "--type", "vfat", "--mountpoint", "/boot/efi"])
        .output()
    {
        let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
        if !s.is_empty() { return Ok(std::path::PathBuf::from(s)); }
    }
    Ok(std::path::PathBuf::from("/boot/efi"))
}

fn find_kernel_initrd() -> Result<(String, String)> {
    let boot = std::path::Path::new("/boot");
    let kernel = std::fs::read_dir(boot)?
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().to_string())
        .filter(|n| n.starts_with("vmlinuz-") && !n.ends_with(".old"))
        .max() // latest = largest name (version sort approximation)
        .map(|k| format!("/boot/{}", k))
        .unwrap_or_else(|| "/boot/vmlinuz".to_string());

    let initrd = kernel.replace("vmlinuz", "initrd.img");
    Ok((kernel, initrd))
}

fn read_current_cmdline() -> Result<String> {
    let cmdline = std::fs::read_to_string("/proc/cmdline")
        .unwrap_or_default();
    // Strip existing hammer.gen= from cmdline
    let cleaned: Vec<&str> = cmdline.split_whitespace()
        .filter(|s| !s.starts_with("hammer.gen=") && !s.starts_with("BOOT_IMAGE="))
        .collect();
    Ok(cleaned.join(" "))
}
