use anyhow::Result;
use owo_colors::OwoColorize;
use std::path::PathBuf;

// ─────────────────────────────────────────────────────────────
//  Top-level commands for completion
// ─────────────────────────────────────────────────────────────

const COMMANDS: &[(&str, &str)] = &[
    ("install",      "Install packages"),
    ("remove",       "Remove packages"),
    ("reinstall",    "Reinstall packages"),
    ("upgrade",      "Upgrade installed packages"),
    ("dist-upgrade", "Aggressive upgrade including new deps"),
    ("autoremove",   "Remove unused auto-installed packages"),
    ("fix-broken",   "Fix broken dependencies"),
    ("sync",         "Refresh package index from repositories"),
    ("self-update",  "Update hammer itself"),
    ("search",       "Search for packages"),
    ("info",         "Show package details"),
    ("list",         "List packages"),
    ("status",       "Show system status"),
    ("history",      "Show transaction history"),
    ("gen",          "Manage generations (list, switch)"),
    ("rollback",     "Roll back to previous generation"),
    ("features",     "Show all feature flags for this build"),
    ("snapshot",     "Create a filesystem snapshot"),
    ("fsck",         "Filesystem check of hammer store"),
    ("check",        "Check package integrity"),
    ("audit",        "Security audit of packages"),
    ("boot",         "Boot management (status, activate, fallback)"),
    ("arch",         "Multi-arch management"),
    ("dpkg-arch",    "dpkg --print-architecture compatible commands"),
    ("repo",         "Manage source repositories (add/remove/list)"),
    ("diff",         "Show diff between generations"),
    ("pending",      "Manage pending changes"),
    ("verify",       "Verify package integrity"),
    ("doctor",       "System health check"),
    ("service",      "Manage systemd services"),
    ("log",          "Show hammer operation log"),
    ("immutable",    "Manage filesystem immutability"),
    ("export",       "Export packages to archive"),
    ("import",       "Import packages from archive"),
    ("key",          "Manage trusted GPG keys"),
    ("gc",           "Garbage-collect old generations"),
    ("clean",        "Clean download cache"),
    ("init",         "Initialise hammer environment"),
    ("relink",       "Relink binaries into PATH"),
    ("store",        "Open Hammer Store GUI"),
    ("pin",          "Pin package versions"),
    ("why",          "Show why a package is installed"),
    ("why-not",      "Show why a package cannot be installed"),
    ("show-deps",    "Show dependency tree"),
    ("files",        "List files installed by package"),
    ("owns",         "Find which package owns a file"),
    ("changelog",    "Show package changelog"),
    ("stats",        "Show store statistics"),
    ("etc",          "Manage config files (diff, reset, show)"),
    ("mirror",       "Mirror a repository locally"),
    ("notify",       "Desktop update notifications"),
    ("sandbox",      "Run application in isolated environment"),
    ("completion",   "Generate shell completions"),
];

const GLOBAL_FLAGS: &[&str] = &[
    "--user", "--arch=", "--yes", "-y", "--help", "-h", "--version",
    "--dry-run", "-n", "--json", "--no-progress", "--debug", "--verbose",
    "--quiet", "--color=always", "--color=never", "--root=", "--force",
"--no-recommends", "--installed", "--upgrades", "--json",
];

// ─────────────────────────────────────────────────────────────
//  Bash completion
// ─────────────────────────────────────────────────────────────

fn bash_completion() -> String {
    let cmds: Vec<&str> = COMMANDS.iter().map(|(c, _)| *c).collect();
    let cmds_str = cmds.join(" ");

    format!(r#"# hammer bash completion — auto-generated by `hammer completion bash`
        # Install: source this file or place in /etc/bash_completion.d/hammer

        _hammer_packages() {{
        # Complete from installed packages via hammer list --installed
        local pkgs
        pkgs=$(hammer list --installed 2>/dev/null | awk '{{print $2}}' | grep -v '^$')
        echo "$pkgs"
}}

_hammer_all_packages() {{
# Complete from cache (may be slow for large repos)
hammer list 2>/dev/null | awk '{{print $2}}' | grep -v '^$'
}}

_hammer_gens() {{
hammer gen list 2>/dev/null | grep -oP 'gen-\K[0-9]+' || true
}}

_hammer_services() {{
hammer service list 2>/dev/null | tail -n +5 | awk '{{print $1}}' | grep '\.service$'
}}

_hammer() {{
local cur prev words cword
_init_completion || return

local commands="{cmds}"

case "${{cword}}" in
1)
        COMPREPLY=( $(compgen -W "$commands" -- "$cur") )
        return 0
        ;;
        esac

        case "${{words[1]}}" in
        install|reinstall|upgrade|info|show-deps|files|why|why-not|changelog)
        # Complete with all available packages
        COMPREPLY=( $(compgen -W "$(_hammer_all_packages)" -- "$cur") )
        ;;
        remove|autoremove|pin)
        # Complete with installed packages only
        COMPREPLY=( $(compgen -W "$(_hammer_packages)" -- "$cur") )
        ;;
        gen)
        case "${{cword}}" in
        2) COMPREPLY=( $(compgen -W "list switch" -- "$cur") ) ;;
        3) COMPREPLY=( $(compgen -W "$(_hammer_gens)" -- "$cur") ) ;;
        esac
        ;;
        service)
        case "${{cword}}" in
        2) COMPREPLY=( $(compgen -W "list start stop restart reload enable disable status log" -- "$cur") ) ;;
        *) COMPREPLY=( $(compgen -W "$(_hammer_services)" -- "$cur") ) ;;
        esac
        ;;
        key)
        COMPREPLY=( $(compgen -W "list add remove" -- "$cur") )
        ;;
        pending)
        COMPREPLY=( $(compgen -W "show cancel apply-live" -- "$cur") )
        ;;
        immutable)
        COMPREPLY=( $(compgen -W "status enable disable unlock install-service" -- "$cur") )
        ;;
        etc)
        case "${{cword}}" in
        2) COMPREPLY=( $(compgen -W "diff reset show" -- "$cur") ) ;;
        *) _filedir ;;
        esac
        ;;
        pin)
        case "${{cword}}" in
        2) COMPREPLY=( $(compgen -W "list add remove hold unhold" -- "$cur") ) ;;
        3) COMPREPLY=( $(compgen -W "$(_hammer_packages)" -- "$cur") ) ;;
        esac
        ;;
        owns)
        _filedir
        ;;
        diff)
        COMPREPLY=( $(compgen -W "$(_hammer_gens)" -- "$cur") )
        ;;
        completion)
        COMPREPLY=( $(compgen -W "bash zsh fish install" -- "$cur") )
        ;;
        *)
        COMPREPLY=( $(compgen -W "{global_flags}" -- "$cur") )
        ;;
        esac
}}

complete -F _hammer hammer
"#,
cmds = cmds_str,
global_flags = GLOBAL_FLAGS.join(" "),
    )
}

// ─────────────────────────────────────────────────────────────
//  Zsh completion
// ─────────────────────────────────────────────────────────────

fn zsh_completion() -> String {
    let mut cmd_spec = String::new();
    for (cmd, desc) in COMMANDS {
        cmd_spec.push_str(&format!("    '{}:{}'\n", cmd, desc));
    }

    format!(r#"#compdef hammer
        # hammer zsh completion — auto-generated by `hammer completion zsh`
        # Install: place in a directory on $fpath, e.g. /usr/share/zsh/vendor-completions/_hammer

        _hammer() {{
        local context state state_descr line
        typeset -A opt_args

        local -a commands
        commands=(
            {cmd_spec}    )

        local -a global_flags
        global_flags=(
            '--user[Operate on user packages]'
    '--arch=[Target architecture]:arch:(amd64 arm64 armhf i386)'
    '--yes[Assume yes to all prompts]'
    '--no-recommends[Skip recommended packages]'
    '--json[Output in JSON format]'
    )

        _arguments -C \
        $global_flags \
        '1:command:->command' \
        '*::args:->args' && return 0

        case $state in
        command)
        _describe 'hammer commands' commands
        ;;
        args)
        case $words[1] in
        install|reinstall|upgrade|info|show-deps|files|why|why-not|changelog)
        local pkgs
        pkgs=(${{(f)"$(hammer list 2>/dev/null | awk '{{print $2}}')"}})
        _describe 'packages' pkgs
        ;;
        remove|autoremove)
        local pkgs
        pkgs=(${{(f)"$(hammer list --installed 2>/dev/null | awk '{{print $2}}')"}})
        _describe 'installed packages' pkgs
        ;;
        gen)
        local subcmds; subcmds=(list switch)
        if (( CURRENT == 2 )); then
            _describe 'gen subcommands' subcmds
            else
                local gens
                gens=(${{(f)"$(hammer gen list 2>/dev/null | grep -oP 'gen-\K[0-9]+')"}})
        _describe 'generations' gens
        fi
        ;;
        service)
        local subcmds; subcmds=(list start stop restart reload enable disable status log)
        if (( CURRENT == 2 )); then
            _describe 'service subcommands' subcmds
            else
                local svcs
                svcs=(${{(f)"$(hammer service list 2>/dev/null | tail -n +5 | awk '{{print $1}}')"}})
        _describe 'services' svcs
        fi
        ;;
        key)
        local subcmds; subcmds=(list add remove)
        _describe 'key subcommands' subcmds
        ;;
        pin)
        local subcmds; subcmds=(list add remove hold unhold)
        if (( CURRENT == 2 )); then
            _describe 'pin subcommands' subcmds
            else
                local pkgs
                pkgs=(${{(f)"$(hammer list --installed 2>/dev/null | awk '{{print $2}}')"}})
        _describe 'packages' pkgs
        fi
        ;;
        etc)
        local subcmds; subcmds=(diff reset show)
        if (( CURRENT == 2 )); then
            _describe 'etc subcommands' subcmds
            else
                _files
                fi
                ;;
            owns)
        _files
        ;;
        completion)
        local shells; shells=(bash zsh fish install)
        _describe 'shells' shells
        ;;
        immutable)
        local subcmds; subcmds=(status enable disable unlock install-service)
        _describe 'immutable subcommands' subcmds
        ;;
        pending)
        local subcmds; subcmds=(show cancel apply-live)
        _describe 'pending subcommands' subcmds
        ;;
        esac
        ;;
        esac
}}

_hammer "$@"
"#,
cmd_spec = cmd_spec,
    )
}

// ─────────────────────────────────────────────────────────────
//  Fish completion
// ─────────────────────────────────────────────────────────────

fn fish_completion() -> String {
    let mut lines = String::new();

    lines.push_str("# hammer fish completion — auto-generated by `hammer completion fish`\n");
    lines.push_str("# Install: place in ~/.config/fish/completions/hammer.fish\n\n");

    // Disable file completions for hammer
    lines.push_str("complete -c hammer -f\n\n");

    // Top-level commands
    for (cmd, desc) in COMMANDS {
        lines.push_str(&format!(
            "complete -c hammer -n '__fish_use_subcommand' -a '{}' -d '{}'\n",
            cmd, desc
        ));
    }

    lines.push('\n');

    // Package-completing commands (all available)
    let pkg_cmds = ["install", "reinstall", "upgrade", "info", "show-deps",
    "files", "why", "why-not", "changelog"];
    for cmd in &pkg_cmds {
        lines.push_str(&format!(
            "complete -c hammer -n '__fish_seen_subcommand_from {}' \
-a '(hammer list 2>/dev/null | string match -r \"^. (\\S+)\" | string replace -r \"^. \" \"\")'\n",
                                cmd
        ));
    }

    lines.push('\n');

    // Installed-package commands
    let inst_cmds = ["remove", "autoremove", "pin"];
    for cmd in &inst_cmds {
        lines.push_str(&format!(
            "complete -c hammer -n '__fish_seen_subcommand_from {}' \
-a '(hammer list --installed 2>/dev/null | string match -r \"^✔ (\\S+)\" | string replace -r \"^✔ \" \"\")'\n",
                                cmd
        ));
    }

    lines.push('\n');

    // Subcommand completions
    lines.push_str("# gen subcommands\n");
    lines.push_str("complete -c hammer -n '__fish_seen_subcommand_from gen' -a 'list switch' -f\n");

    lines.push_str("# service subcommands\n");
    lines.push_str("complete -c hammer -n '__fish_seen_subcommand_from service' \
-a 'list start stop restart reload enable disable status log' -f\n");

    lines.push_str("# key subcommands\n");
    lines.push_str("complete -c hammer -n '__fish_seen_subcommand_from key' -a 'list add remove' -f\n");

    lines.push_str("# pin subcommands\n");
    lines.push_str("complete -c hammer -n '__fish_seen_subcommand_from pin' \
-a 'list add remove hold unhold' -f\n");

    lines.push_str("# pending subcommands\n");
    lines.push_str("complete -c hammer -n '__fish_seen_subcommand_from pending' \
-a 'show cancel apply-live' -f\n");

    lines.push_str("# immutable subcommands\n");
    lines.push_str("complete -c hammer -n '__fish_seen_subcommand_from immutable' \
-a 'status enable disable unlock install-service' -f\n");

    lines.push_str("# etc subcommands\n");
    lines.push_str("complete -c hammer -n '__fish_seen_subcommand_from etc' \
-a 'diff reset show' -f\n");

    lines.push_str("# completion subcommands\n");
    lines.push_str("complete -c hammer -n '__fish_seen_subcommand_from completion' \
-a 'bash zsh fish install' -f\n");

    lines.push('\n');

    // Global flags
    lines.push_str("# Global flags\n");
    lines.push_str("complete -c hammer -l user         -d 'Operate on user packages'\n");
    lines.push_str("complete -c hammer -l yes  -s y    -d 'Assume yes'\n");
    lines.push_str("complete -c hammer -l json          -d 'JSON output'\n");
    lines.push_str("complete -c hammer -l no-recommends -d 'Skip recommends'\n");
    lines.push_str("complete -c hammer -l arch \
-a 'amd64 arm64 armhf i386 riscv64' -d 'Target architecture'\n");

    lines
}

// ─────────────────────────────────────────────────────────────
//  CLI entry point
// ─────────────────────────────────────────────────────────────

pub fn cmd_completion(args: &[String]) -> Result<()> {
    let shell = args.first().map(|s| s.as_str()).unwrap_or("bash");

    match shell {
        "bash" => {
            print!("{}", bash_completion());
        }
        "zsh" => {
            print!("{}", zsh_completion());
        }
        "fish" => {
            print!("{}", fish_completion());
        }
        "install" => {
            install_completions(args)?;
        }
        other => {
            anyhow::bail!(
                "Unknown shell '{}'. Supported: bash, zsh, fish, install", other
            );
        }
    }
    Ok(())
}

fn install_completions(args: &[String]) -> Result<()> {
    let shell = args.iter()
    .find(|a| a.starts_with("--shell="))
    .and_then(|a| a.strip_prefix("--shell="))
    .unwrap_or("all");

    let shells: Vec<&str> = if shell == "all" {
        vec!["bash", "zsh", "fish"]
    } else {
        vec![shell]
    };

    for s in shells {
        match s {
            "bash" => {
                let path = PathBuf::from("/etc/bash_completion.d/hammer");
                std::fs::create_dir_all(path.parent().unwrap())?;
                std::fs::write(&path, bash_completion())?;
                println!("  {} bash completion → {}", "✔".bright_green(), path.display());
            }
            "zsh" => {
                // Try system zsh first, then user
                let paths = [
                    PathBuf::from("/usr/share/zsh/vendor-completions/_hammer"),
                    PathBuf::from("/usr/local/share/zsh/site-functions/_hammer"),
                ];
                let path = paths.iter().find(|p| p.parent().map_or(false, |d| d.exists()))
                .unwrap_or(&paths[0]);
                std::fs::create_dir_all(path.parent().unwrap())?;
                std::fs::write(path, zsh_completion())?;
                println!("  {} zsh completion  → {}", "✔".bright_green(), path.display());
            }
            "fish" => {
                let home = std::env::var("HOME").unwrap_or_else(|_| "/root".into());
                let path = PathBuf::from(&home)
                .join(".config/fish/completions/hammer.fish");
                std::fs::create_dir_all(path.parent().unwrap())?;
                std::fs::write(&path, fish_completion())?;
                println!("  {} fish completion → {}", "✔".bright_green(), path.display());
            }
            _ => {}
        }
    }

    println!();
    println!("  Restart your shell or run {} to activate.",
             "exec $SHELL".cyan());
    Ok(())
}
